// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCKg3_3F_huC5eUXMZx4ntiP5crYPO8_8',
    appId: '1:335860246922:android:f23418aee5bdcc51c24073',
    messagingSenderId: '335860246922',
    projectId: 'aula-11-dm',
    storageBucket: 'aula-11-dm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB089wSO0k2mEw5dLYy8Wio5ZlCVxaUChA',
    appId: '1:335860246922:ios:369439adfb41bce8c24073',
    messagingSenderId: '335860246922',
    projectId: 'aula-11-dm',
    storageBucket: 'aula-11-dm.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9HszJhK8pRlmU4ktNu4AlhNBbo49zmc',
    appId: '1:335860246922:web:767a060e88090f5fc24073',
    messagingSenderId: '335860246922',
    projectId: 'aula-11-dm',
    authDomain: 'aula-11-dm.firebaseapp.com',
    storageBucket: 'aula-11-dm.firebasestorage.app',
    measurementId: 'G-KY7B8HPZP7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB089wSO0k2mEw5dLYy8Wio5ZlCVxaUChA',
    appId: '1:335860246922:ios:369439adfb41bce8c24073',
    messagingSenderId: '335860246922',
    projectId: 'aula-11-dm',
    storageBucket: 'aula-11-dm.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx9HszJhK8pRlmU4ktNu4AlhNBbo49zmc',
    appId: '1:335860246922:web:6788fd595387cf1fc24073',
    messagingSenderId: '335860246922',
    projectId: 'aula-11-dm',
    authDomain: 'aula-11-dm.firebaseapp.com',
    storageBucket: 'aula-11-dm.firebasestorage.app',
    measurementId: 'G-XL1H87SH7Y',
  );

}